In [5]:
# 1. 导入Numpy库，通常简写为np
import numpy as np

# 2. 从Python列表创建一个一维Numpy数组
my_list = [1, 2, 3, 4, 5]
np_array_1d = np.array(my_list)

print("--- 一维数组 ---")
print(f"这是一个Numpy数组: {np_array_1d}")
print(f"它的类型是: {type(np_array_1d)}") # <class 'numpy.ndarray'>

# 3. 查看数组的属性
print(f"数组的维度 (秩): {np_array_1d.ndim}")    # 1
print(f"数组的形状 (shape): {np_array_1d.shape}") # (5,)
print(f"数组中元素的类型: {np_array_1d.dtype}")  # int32 (根据你的系统可能不同)

# 4. 从嵌套列表创建一个二维数组 (矩阵)
my_nested_list = [[1, 2, 3], [4, 5, 6]]
np_array_2d = np.array(my_nested_list)

print("\n--- 二维数组 ---")
print("这是一个二维数组:")
print(np_array_2d)
print(f"二维数组的维度: {np_array_2d.ndim}")    # 2
print(f"二维数组的形状: {np_array_2d.shape}") # (2, 3) -> 2行3列
print(f"数组中元素的总数: {np_array_2d.size}") # 6

--- 一维数组 ---
这是一个Numpy数组: [1 2 3 4 5]
它的类型是: <class 'numpy.ndarray'>
数组的维度 (秩): 1
数组的形状 (shape): (5,)
数组中元素的类型: int64

--- 二维数组 ---
这是一个二维数组:
[[1 2 3]
 [4 5 6]]
二维数组的维度: 2
二维数组的形状: (2, 3)
数组中元素的总数: 6


In [6]:
# --- 数组创建 ---
print("--- 数组创建 ---")
# 创建一个全是0的数组
zeros_array = np.zeros((2, 4)) # 创建一个2行4列的全0数组
print("全0数组:")
print(zeros_array)

# 创建一个全是1的数组
ones_array = np.ones((3, 2)) # 创建一个3行2列的全1数组
print("\n全1数组:")
print(ones_array)

# 创建一个等差序列数组 (类似Python的range)
range_array = np.arange(10, 20, 2) # 从10开始，到20结束(不含)，步长为2
print(f"\n等差序列数组: {range_array}")

# 创建一个指定数量的等间隔数组
linspace_array = np.linspace(0, 1, 5) # 从0到1，均匀取5个点
print(f"\n等间隔数组: {linspace_array}")

# 创建一个随机数组
random_array = np.random.rand(2, 3) # 创建一个2x3的，0到1之间的随机数数组
print("\n随机数组:")
print(random_array)

# --- 索引与切片 ---
print("\n--- 索引与切片 ---")
a = np.arange(10) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(f"原始数组a: {a}")

# 基本切片 (和Python列表类似)
print(f"a的第2到第5个元素: {a[2:5]}")     # [2, 3, 4]
print(f"a的前4个元素: {a[:4]}")          # [0, 1, 2, 3]
print(f"a从第4个元素开始到结尾: {a[4:]}") # [4, 5, 6, 7, 8, 9]

# 二维数组索引 (非常重要！)
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("\n二维数组b:")
print(b)

# 获取单个元素: b[行, 列]
element = b[1, 2] # 第1行，第2列 (索引从0开始) -> 7
print(f"\nb的第1行第2列元素是: {element}")

# 获取整行或整列
row_1 = b[1, :] # 第1行所有列
print(f"b的第1行: {row_1}")

col_2 = b[:, 2] # 所有行，第2列
print(f"b的第2列: {col_2}")

# 获取子矩阵
sub_matrix = b[:2, 1:3] # 前2行 (0,1), 第1、2列
print("\nb的子矩阵 (前2行，1、2列):")
print(sub_matrix)

# 布尔索引 (非常强大！)
# 找出数组b中所有大于5的元素
bool_mask = b > 5
print("\n布尔掩码 (b > 5):")
print(bool_mask)

print("\n通过布尔掩码筛选出的元素:")
print(b[bool_mask]) # 或者直接写 b[b > 5]

--- 数组创建 ---
全0数组:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

全1数组:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

等差序列数组: [10 12 14 16 18]

等间隔数组: [0.   0.25 0.5  0.75 1.  ]

随机数组:
[[0.49984117 0.84739509 0.02704845]
 [0.05003639 0.95012381 0.37161148]]

--- 索引与切片 ---
原始数组a: [0 1 2 3 4 5 6 7 8 9]
a的第2到第5个元素: [2 3 4]
a的前4个元素: [0 1 2 3]
a从第4个元素开始到结尾: [4 5 6 7 8 9]

二维数组b:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

b的第1行第2列元素是: 7
b的第1行: [5 6 7 8]
b的第2列: [ 3  7 11]

b的子矩阵 (前2行，1、2列):
[[2 3]
 [6 7]]

布尔掩码 (b > 5):
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]

通过布尔掩码筛选出的元素:
[ 6  7  8  9 10 11 12]


In [7]:
# --- 向量化运算 ---
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [9]:
print("--- 逐元素运算 ---")
print("x + y:")
print(x + y)

print("\nx - y:")
print(x - y)

print("\nx * y (逐元素相乘):")
print(x * y)

print("\nx / y (逐元素相除):")
print(x / y)

print("\nsqrt(x) (逐元素开方):")
print(np.sqrt(x))

--- 逐元素运算 ---
x + y:
[[ 6  8]
 [10 12]]

x - y:
[[-4 -4]
 [-4 -4]]

x * y (逐元素相乘):
[[ 5 12]
 [21 32]]

x / y (逐元素相除):
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

sqrt(x) (逐元素开方):
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [11]:
# --- 矩阵乘法 (点积) ---
print("\n--- 矩阵乘法 ---")
# 两种方式，效果相同
dot_product_1 = np.dot(x, y)
dot_product_2 = x @ y
print("x @ y (矩阵乘法):")
print(dot_product_2)


--- 矩阵乘法 ---
x @ y (矩阵乘法):
[[19 22]
 [43 50]]


In [12]:
# --- 聚合运算 ---
print("\n--- 聚合运算 ---")
data = np.array([[1, 2, 3], [4, 5, 6]])
print("原始数据:")
print(data)

print(f"所有元素的和: {np.sum(data)}")
print(f"所有元素的平均值: {np.mean(data)}")
print(f"所有元素的最大值: {np.max(data)}")


--- 聚合运算 ---
原始数据:
[[1 2 3]
 [4 5 6]]
所有元素的和: 21
所有元素的平均值: 3.5
所有元素的最大值: 6


In [13]:
# 沿指定轴(axis)运算
# axis=0: 沿着列的方向进行计算 (对每一列求和)
# axis=1: 沿着行的方向进行计算 (对每一行求和)
print(f"\n按列求和 (axis=0): {np.sum(data, axis=0)}") # [1+4, 2+5, 3+6] -> [5, 7, 9]
print(f"按行求和 (axis=1): {np.sum(data, axis=1)}") # [1+2+3, 4+5+6] -> [6, 15]


按列求和 (axis=0): [5 7 9]
按行求和 (axis=1): [ 6 15]


In [17]:
print(f"np_array_1d的和为：{np.sum(np_array_1d, axis=0)}")

np_array_1d的和为：15


In [18]:
# --- 广播 (Broadcasting) ---
# Numpy的另一个强大特性：可以对不同形状的数组进行运算
print("\n--- 广播 ---")
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([10, 20, 30])

# 将vector广播到matrix的每一行进行相加
result = matrix + vector
print("矩阵 + 向量 (广播):")
print(result)


--- 广播 ---
矩阵 + 向量 (广播):
[[11 22 33]
 [14 25 36]
 [17 28 39]]


理解与思考：
向量化是核心！永远优先使用 x + y 这样的向量化操作，而不是用for循环遍历数组元素再相加。
x * y 和 x @ y 是完全不同的运算，前者是对应元素相乘，后者是标准的矩阵乘法。这是初学者常犯的错误。
广播机制非常强大，它使得代码更简洁。其规则是：如果两个数组的形状不匹配，Numpy会尝试扩展（“广播”）较小数组的形状，以使其与较大数组的形状兼容。