In [ ]:
import numpy as np
import torch

# 打印PyTorch版本
print(f"PyTorch version: {torch.__version__}")

# 检查GPU是否可用
is_gpu_available = torch.cuda.is_available()
print(f"GPU is available: {is_gpu_available}")

PyTorch version: 2.7.1
GPU is available: False


In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"tensor from list: {x_data}")

tensor from list: tensor([[1, 2],
        [3, 4]])


In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"tensor from numpy: {x_np}")

tensor from numpy: tensor([[1, 2],
        [3, 4]])


In [5]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [6]:
# --- Tensor Operations ---
tensor = torch.ones(2, 3)  # 创建一个 2x3 的全1张量
print(f"Original tensor:\n {tensor}\n")

# 1. 索引和切片 (和Numpy一样)
first_row = tensor[0]
first_column = tensor[:, 0]
last_element = tensor[-1, -1]
print(f"First row: {first_row}")
print(f"First column: {first_column}")
print(f"Last element: {last_element}\n")

# 2. 拼接 Tensors
# dim=1 表示按列（水平）拼接
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f"Concatenated tensor (dim=1):\n {t1}\n")

# 3. 数学运算
# 矩阵乘法
y1 = tensor @ tensor.T  # .T 是转置 (transpose)
y2 = torch.matmul(tensor, tensor.T)
print(f"Matrix multiplication result:\n {y1}\n")

# 逐元素运算
z1 = tensor * tensor  # 对应元素相乘
z2 = tensor.mul(tensor)
print(f"Element-wise multiplication result:\n {z1}\n")

# 单一元素Tensor
# 如果一个tensor只有一个元素，可以用.item()来获取它的Python数值
agg = tensor.sum()
agg_item = agg.item()
print(f"Sum of all elements: {agg_item}, Type: {type(agg_item)}")

Original tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

First row: tensor([1., 1., 1.])
First column: tensor([1., 1.])
Last element: 1.0

Concatenated tensor (dim=1):
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Matrix multiplication result:
 tensor([[3., 3.],
        [3., 3.]])

Element-wise multiplication result:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Sum of all elements: 6.0, Type: <class 'float'>
